### ISSUE TITLE
Add config to change the php version

### ISSUE THREAD

**Issue by ossie** [dartcafe/all-inkl-nc-updater#4]
I would appreciate an update safe parameter to set the php version to use in the bash.

**Comment by dartcafe** [comment]
Just set a link in your `.user_bashrc` file
i.e. `ln -sfv /usr/bin/php81 /usr/bin/php`

Explanation see also here: https://all-inkl.com/wichtig/anleitungen/kas/ssh/dateiverwaltung/aenderung-der-php-cli-version_527.html

**Comment by ossie** [comment]
Fair enough, this will also work. Thanks for the hint to the docu.
